### ISSUE TITLE
Add NPM Module support

### ISSUE THREAD

**Issue by wgyt** [wgytcraft/hosting#20]
**Is your feature request related to a problem? Please describe.**
We should add support for npm modules as wgytcraft modules using the `npm://` followed by the package name
**Describe alternatives you've considered**
You could use local/git modules, but this is cool idea
**Additional context**
NPM dependencies are easier to maintain then git ones
**CC:**
@retronbv

**Comment by retronbv** [comment]
I don't see why people would submit wgytcraft packages to npm? It doesn't make any sense

**Comment by wgyt** [comment]
> I don't see why people would submit wgytcraft packages to npm? It doesn't make any sense

we just published wgytcraft to npm, this could streamline the process
