### ISSUE TITLE
[dependencies] fork ejs or move to eta?

### ISSUE THREAD

**Issue by wgyt** [wgytcraft/hosting#28]
https://www.npmjs.com/package/eta has less dependencies then https://www.npmjs.com/package/ejs (0 compared to 1 that has more) and it is compatible
https://eta.js.org/docs/about/eta-vs-ejs

**Comment by GrahamSH-LLK** [comment]
Nice!

**Comment by wgyt** [comment]
reopening because eta breaks when we use it in wgytcraft/errors

**Comment by wgyt** [comment]
@GrahamSH-LLK ejs doesn't need any of its dependencies, should we fork ejs instead of moving to eta?
