### ISSUE TITLE
[documentation] document modules.json and stuff

### ISSUE THREAD

**Issue by wgyt** [wgytcraft/hosting#3]
^^

**Comment by wgyt** [comment]
This is more in the scope of [wgytwebsites/documentation.wgyt.tk](https://github.com/wgytwebsites/documentation.wgyt.tk) unless we setup docs.wgytcraft.cf or something

**Comment by retronbv** [comment]
We should setup docs.wgytcraft.cf

**Comment by wgyt** [comment]
@retronbv would you want to help setup the module that we would need for that?

**Comment by retronbv** [comment]
> @retronbv would you want to help setup the module that we would need for that?

huh

**Comment by retronbv** [comment]
@wgyt What module would we need?

**Comment by wgyt** [comment]
> @wgyt What module would we need?

we would need to make one

**Comment by retronbv** [comment]
> > @wgyt What module would we need?
> 
> we would need to make one

Make a repl and invite me

**Comment by wgyt** [comment]
fixed in https://github.com/wgytcraft/errors/commit/9450212249ce5933b440f28f6b7e8339f75dd8b3
