### ISSUE TITLE
Add config files for modules

### ISSUE THREAD

**Issue by wgyt** [wgytcraft/hosting#36]
just let modules have an object like this:
```json
{
...
	"websiteData":{
		"test.wgyt.tk":{
			"module":"wgytcraft/hello-world-template",
			"config":{}
		}
	}
}
```

**Comment by wgyt** [comment]
this would break all old modules, I think.
@GrahamSH-LLK would this break old modules?

**Comment by GrahamSH-LLK** [comment]
There are like no old modules, so who cares
