### ISSUE TITLE
transition to typescript

### ISSUE THREAD

**Issue by thecoder876** [wgytcraft/hosting#42]
chat about the transition to typescript
also vote if we should transition using the thumbs up and down emojis

**Comment by thecoder876** [comment]
this was too early, need to set up gh updates first

**Comment by wgyt** [comment]
done

**Comment by thecoder876** [comment]
@wgyt add milestone and project

**Comment by wgyt** [comment]
> @wgyt add milestone and project

sure, one second

**Comment by thecoder876** [comment]
and pin it

**Comment by thecoder876** [comment]
moved to #43
