### ISSUE TITLE
contributors: get recognized

### ISSUE THREAD

**Issue by wgyt** [wgytcraft/hosting#9]
To add yourself you need to write a reply with the following info:
> @all-contributors please add @username for contributions

replacing username with the person you want added and replacing contributions with something from the [emoji key](https://allcontributors.org/docs/en/emoji-key)

**Comment by wgyt** [comment]
@all-contributors please add @wgyt for bug, code, doc, design, example, ideas, infra, maintenance and review

**Comment by wgyt** [comment]
@all-contributors please add @wgyt for bug, code, doc, design, example, ideas, infra, maintenance and review

**Comment by wgyt** [comment]
Thanks @retronbv for the help with issue #6 and your code and ideas!
cc @all-contributors

**Comment by wgyt** [comment]
@all-contributors please add @retronbv  for code and ideas

**Comment by wgyt** [comment]
@all-contributors please add @thecoder876 for code

**Comment by GrahamSH-LLK** [comment]
@all-contributors please add @GrahamSH-LLK for code

**Comment by wgyt** [comment]
this is ongoing thing, but it isn't an issue

**Comment by wgyt** [comment]
@all-contributors please add @GrahamSH-LLK for docs

**Comment by thecoder876** [comment]
@all-contributors please add @thecoder876 for ideas, maintenance, projectManagement and review

**Comment by wgyt** [comment]
@all-contributors please add @GrahamSH-LLK for bugs, code, ideas, review, and tests

**Comment by retronbv** [comment]
@all-contributors please add @retronbv for bugs, review, maintenance, and tests

**Comment by cary-uwu** [comment]
@all-contributors please add @cary-uwu for ideas
